#!/usr/bin/env bash

export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/plugins"
printf -v PLUGIN_COMMAND_DIR '%q' "$PLUGIN_DIR"

sketchybar --bar \
  height=32 \
  position=top \
  color=0xff1e1e2e \
  shadow=off \
  sticky=on \
  padding_left=12 \
  padding_right=12 \
  corner_radius=0 \
  margin=0 \
  y_offset=0

sketchybar --default \
  icon.font="SF Pro:Medium:12.0" \
  label.font="SF Pro:Medium:12.0" \
  icon.color=0xffcdd6f4 \
  label.color=0xffcdd6f4 \
  icon.padding_left=8 \
  icon.padding_right=8 \
  label.padding_left=6 \
  label.padding_right=8 \
  padding_left=3 \
  padding_right=3 \
  background.height=22 \
  background.corner_radius=6

sketchybar --add event aerospace_workspace_change

for sid in 1 2 3 4 5 6 7 8 9; do
  sketchybar --add item "space.$sid" left \
    --set "space.$sid" \
      icon="$sid" \
      icon.width=28 \
      icon.align=center \
      icon.padding_left=0 \
      icon.padding_right=0 \
      label.drawing=off \
      click_script="aerospace workspace $sid" \
      script="$PLUGIN_COMMAND_DIR/workspace.sh $sid" \
    --subscribe "space.$sid" aerospace_workspace_change
done

sketchybar --add item front_app left \
  --set front_app icon.drawing=off label.max_chars=22 label.color=0xffbac2de \
    padding_left=12 script="$PLUGIN_COMMAND_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

sketchybar --add item clock right \
  --set clock icon.drawing=off label.font="SF Pro:Semibold:12.0" \
    label.padding_left=12 label.padding_right=4 update_freq=10 \
    script="$PLUGIN_COMMAND_DIR/clock.sh"

sketchybar --add item battery right \
  --set battery icon.drawing=off label.color=0xffa6adc8 \
    label.padding_left=12 label.padding_right=12 \
    background.drawing=on background.color=0xff313244 \
    update_freq=60 script="$PLUGIN_COMMAND_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

sketchybar --update
